### ISSUE TITLE
Can't find the file of 'data/cifar10/train.txt'

### ISSUE THREAD

**Issue by hongge831** [thulab/DeepHash#1]
Hi there, I just cant find the dir 'data/cifar10/train.txt', can you provide it?

**Comment by yunfei-shi** [comment]
May help. https://github.com/caoyue10/cvpr17-dvsq/tree/aaai16-dqn/data/nuswide_21

**Comment by bl0** [comment]
Hi, Sorry for the late reply. I've updated the readme for more detail about the dataset. Feel free to contact us if you still have any questions.
