### ISSUE TITLE
I meet problem in DVSQ

### ISSUE THREAD

**Issue by freehome1** [thulab/DeepHash#10]
I have ran DTQ successfully and get trouble in DVSQ.  
I meet this problem:
![image](https://user-images.githubusercontent.com/32356286/48553603-027bfd80-e917-11e8-9e3e-fae330012c19.png)
I debug it and find that 
![image](https://user-images.githubusercontent.com/32356286/48553417-7ec21100-e916-11e8-8aa6-bc94ec0b3267.png)
The images and labels are null and I wonder why.

**Comment by freehome1** [comment]
I have checked that the img_dataset just like it in DTQ. However, the function next_batch has return right images and labels in DTQ while [] in DVSQ. I met this problem in DQN too.

**Comment by bl0** [comment]
Hi, can you send your executing command and the full training log to my email(liubinthss@gmail.com)?
Thanks for your help.

**Comment by bl0** [comment]
Hi, I found the reason. You should modify the `/dir/to/dataset/root/` to the root directory of the dataset  In the `train_val.sh`. Sorry for the inconvenience.

For example:
```bash
python train_val_script.py      $lr 300     5000    $q_lambda   4      $dataset    $gpu   $log_dir ../../data/nuswide_81
```

**Comment by freehome1** [comment]
It helps me a lot. Thanks a lot for your patience.
