### ISSUE TITLE
When label information is not available and similarity information is available

### ISSUE THREAD

**Issue by liut0012** [thulab/DeepHash#15]
The input of the algorithm DCH are images and their similarities, but the code takes only the images and their one-hot label coding. 

My data naturally has pairwise similarity information but not label information. So I want to modify the code such that it can accept similarity as input rather than class labels.

Could you help give some advice on which file I should modify?

**Comment by bl0** [comment]
You need to modify the loss function and evaluation codes.

**Comment by bl0** [comment]
I am closing this issue due to the long time of inactivity, feel free to reopen it if there is any question. Thanks!
