### ISSUE TITLE
你好，我运行dvsq的代码时候出现了valueerror，

### ISSUE THREAD

**Issue by ShenQuanYang** [thulab/DeepHash#16]
你好，我在Linux下用CUDA_VISIBLE_DEVICES=1 python train_val_script.py 0.02 300 5000 0.0001 4 cifar10 1 log_dir data/cifar10运行dvsq的程序时出现了一个ValueError：cannot feed value of shape (0,) for Tensor 'Placeholder:0', which has shape '(?, 256, 256, 3)' ，这个问题应该怎么解决呢？？？ 
附件图片中有详细信息
![image001](https://user-images.githubusercontent.com/9738705/50262686-7a28d500-044d-11e9-9617-9945a335aaa6.jpg)

非常期待你的回复，谢谢。

**Comment by bl0** [comment]
看起来是图片路径出问题了，可以检查一下图片在不在对应的位置。

**Comment by ShenQuanYang** [comment]
包含图片的文件夹应该放在那里呢？？？

**Comment by ShenQuanYang** [comment]
cifar10文件分几个文件夹，具体怎么放在那里？？？
非常感谢你回复！！！

**Comment by bl0** [comment]
参考Readme：

Make sure the tree of `/path/to/project/data/cifar10` looks like this:

```
.
|-- database.txt
|-- test
|-- test.txt
|-- train
`-- train.txt
```

**Comment by ShenQuanYang** [comment]
真正的图片数据该怎么放呢？

**Comment by bl0** [comment]
图片放在test和train目录下面

**Comment by ShenQuanYang** [comment]
test和train都和examples的dvsq下吗    和train_val_script.py放在一起？

**Comment by bl0** [comment]
I am closing this issue due to the long time of inactivity, feel free to reopen it if there is any question. Thanks!
