### ISSUE TITLE
dhc tain_val_script

### ISSUE THREAD

**Issue by world2025** [thulab/DeepHash#17]
hello,i met a problem when i run the tain_val_script.py
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: fc6_1/biases/Assign = Assign[T=DT_FLOAT, _class=["loc:@fc6_1/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fc6_1/biases, fc6_1/biases/initial_value)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Is there not enough memory?

**Comment by bl0** [comment]
Yes, pls make sure your GPU has enough memory, or you can reduce the batch size.

**Comment by world2025** [comment]
ok,thanks,when i set the batch size =1,the loss is nan

**Comment by bl0** [comment]
Yes, if the batch size = 1, the loss will be ill-defined.

**Comment by world2025** [comment]
ok,thanks
