### ISSUE TITLE
Rs required in DCH

### ISSUE THREAD

**Issue by liut0012** [thulab/DeepHash#18]
Hi, for each dataset there is a parameter call "Rs". The value for cifar10 is 54000. May I know what this parameter controls? Could you give some advice on how to specific this parameter? 

Thanks a lot!

**Comment by bl0** [comment]
Hi, this parameter controls the Radius you want to calculate for mAP score. For cifar10, 54000 means all data in the `database` split.

**Comment by liut0012** [comment]
Hi, so if Rs is smaller than the number of data in the database, the mAP calculation will stops when the number of retrieved items is larger than this parameter?

**Comment by bl0** [comment]
Yes!

**Comment by bl0** [comment]
I am closing this issue, feel free to reopen it if there is any question. Thanks!

**Comment by fantasy4335** [comment]
I have some questions about Rs. If each category in database.txt have about 30 samples, how should I define the Rs for this dataset? 30?

**Comment by bl0** [comment]
Yes!
The map@R is only a metric to evaluate the performance of the model, so the R actually can be any valid number(In your case, any number <= 30). The only requirement is that you should comare all methods in a same metric, i.e, same R.
