### ISSUE TITLE
Need more detailed documentation.

### ISSUE THREAD

**Issue by orrrrz** [thulab/DeepHash#2]
where is `data/cifar10/train.txt`?
How can I just use it for inference?
How can I replace it with my own component(e.g., to replace AlexNet) ?

**Comment by bl0** [comment]
Hi, I updated the readme about the data/cifar10/train.txt.

If you want to just evaluate, just running with --evaluate parameter.

If you want to replace AlexNet, Just implement the architecture in `DeepHash/DeepHash/architecture/`, then you can import and replace AlexNet with the new architecture.
For example, in dch, you need to replace [line 17](https://github.com/thulab/DeepHash/blob/acaa11696465cc2f404f820752bea3b41681c48e/DeepHash/model/dch/dch.py#L17) and [line 60](https://github.com/thulab/DeepHash/blob/acaa11696465cc2f404f820752bea3b41681c48e/DeepHash/model/dch/dch.py#L60)
