### ISSUE TITLE
'dch' is not compatible with the paper

### ISSUE THREAD

**Issue by maestrojeong** [thulab/DeepHash#20]
Look at the equation 2 in [Deep Cauchy Hashing for Hamming Space Retrieval](http://ise.thss.tsinghua.edu.cn/~mlong/doc/deep-cauchy-hashing-cvpr18.pdf).

It says that 
            w_ij = |S|/|S_1| when s_{i,j}=1 otherwise |S|/|S_0|
But in the [code](https://github.com/thulab/DeepHash/blob/master/DeepHash/model/dch/dch.py#L116) ,
            w_ij = |S|/|S_1| when s_{i,j}=1 otherwise1 

Did you approximate |S|/|S_0| as 1?
Thank you.

**Comment by bl0** [comment]
Yes, and Thanks.
