### ISSUE TITLE
想问一下训练参数，关于DTQ的

### ISSUE THREAD

**Issue by JieLi1994** [thulab/DeepHash#21]
你好，你可以提供一下文章中使用的模型的训练参数吗？《Deep Triplet Quantization》

**Comment by bl0** [comment]
你好，cifar10可以直接用默认参数，nuswide，coco的话把--n-part调成200就行，coco还需要把--triplet-margin调成10。

**Comment by JieLi1994** [comment]
@bl0  谢谢，每个模型都要训100个epoch这么久吗？

**Comment by bl0** [comment]
收敛会很快，但是训练100 epoch的话效果会稍微好一点点。你可以依据你的条件看要不要训练那么久，如果在实验阶段的话20个epoch效果就已经差不多了。

**Comment by JieLi1994** [comment]
@bl0 非常感谢解答我的问题

**Comment by bl0** [comment]
不客气

**Comment by JieLi1994** [comment]
@bl0 可以留个微信吗

**Comment by bl0** [comment]
私聊
