### ISSUE TITLE
Questions on train.txt

### ISSUE THREAD

**Issue by yezi2949** [thulab/DeepHash#22]
If I want to train my data set，If I'm going to train my data set, how do I tag something like 0100 0000?

**Comment by bl0** [comment]
You can just sort the labels in any order. And for each image x_i, let the `j`-th  bit to be 1 if and only if x_i belongs to `j`-th classes.

**Comment by yezi2949** [comment]
thank you  
I thought the name of the picture was similar to 1-22, and 1 was the meaning of category ,yesterday。
