### ISSUE TITLE
when training dch,results run to a worse direction.leading to a bad precision,Map,recall.somebody who can tell me ?

### ISSUE THREAD

**Issue by ssli23** [thulab/DeepHash#23]

**Comment by ssli23** [comment]
sorry.it lead to a good recall.bad precision.bad map.can somebody help me ?thanks a lot

**Comment by bl0** [comment]
Hi, sorry for the late response. Can you describe your problem and operations detailly? What dataset you used and what's the command you run? Furthermore, can you attach the log file?

**Comment by bl0** [comment]
I am closing this issue due to the long time of inactivity, feel free to reopen it if there is any question. Thanks!
