### ISSUE TITLE
DCH How can I get 10 similar images in the paper?

### ISSUE THREAD

**Issue by yezi2949** [thulab/DeepHash#24]

**Comment by bl0** [comment]
For each query images, You can calculate the distance to the database images, then it's easy to get the top-10 images.

**Comment by yezi2949** [comment]
I don't know which parameter isthe distance to the database images，like this Results ham dist [0], prec:0.7461538461538462, rec:1.0, mAP:0.7602980792257076 ?

**Comment by bl0** [comment]
Inner product distance.

**Comment by yezi2949** [comment]
Because my code is not strong, so I would like to ask you how to calculate the distance, I looked at the distance file, but I found that the train_val_script function does not calculate the distance, so I would like to ask you how to call the Inner_produc function?
