### ISSUE TITLE
Inner_produc

### ISSUE THREAD

**Issue by yezi2949** [thulab/DeepHash#25]
Because my code is not strong, so I would like to ask you how to calculate the distance, I looked at the distance file, but I found that the train_val_script function does not calculate the distance, so I would like to ask you how to call the Inner_produc function?

**Comment by yezi2949** [comment]
I already know how to calculate inner-product, but I want to know the difference between get_mAPs_by_feature  and get_mAPs_after_sign

**Comment by bl0** [comment]
get_mAPs_after_sign first take sign operation to the feature, then
calculate the mAP as get_mAPs_by_feature.

**Comment by yezi2949** [comment]
I still have the last question,
1.What is idatebase_output and query.output？like:
[[ 0.8381 0.5619 -0.6921 ... -0.2869 0.7971 0.3359]]
  ...
  [0.7866 0.6371 -0.797 ... -0.3144 0.7996 0.6668]] 
I hope you can help me Explanation it
2. I need to output the most similar image. I found dist, idx. I want to ask if the first few images of idx are the closest ones, or the last ones?
THANKS!

**Comment by bl0** [comment]
1. The database output and query output are continuous features, which is
just the output of Alexnet.
2. The first few images in idx are the closest ones.
