### ISSUE TITLE
question about dch

### ISSUE THREAD

**Issue by DesireHope** [thulab/DeepHash#26]
为什么计算dist的时候要加这个0.001？

**Comment by bl0** [comment]
您好，哪里加了0.001？您能把那行代码的链接发一下吗？

**Comment by DesireHope** [comment]
https://github.com/thulab/DeepHash/blob/0990a8d9760a37f5f41b0f9dbeb0173bbea614e3/DeepHash/model/dch/dch.py#L109

**Comment by bl0** [comment]
应该是当初随手加了防止dist为0产生数值问题，不过实际上应该没有影响。可以去掉它。

**Comment by DesireHope** [comment]
好的，谢谢解答
