### ISSUE TITLE
What are the parameters that control the bit in quantization baesd methodes?

### ISSUE THREAD

**Issue by chenshen03** [thulab/DeepHash#27]
Are bits are controlled by parameter `n_subcenter` and `n_subspace`?

If `n_subcenter=256` and `n_subspace=4` , then the bit is computed as follows:

B = 4 * log(256) = 32

**Comment by bl0** [comment]
Yes!

**Comment by chenshen03** [comment]
@bl0 
How to set the n_subcenter and n_subspace when bits equals 12?
B = 2 * log(64) or B = 3 * log(16) = 12 or B = 4 * log(8) ?
Thank you.

**Comment by bl0** [comment]
I recommend B = 2 * log(64). But you can also try other settings and compare their performance.
