### ISSUE TITLE
mAP on cifar10 is higher than that of dqn paper

### ISSUE THREAD

**Issue by chenshen03** [thulab/DeepHash#29]
I use default settings and data to train dqn, and the mAP of 32bit on cifar10 is 0.6737. However, the mAP on dqn paper is only 0.564. What led to this difference?

![image](https://user-images.githubusercontent.com/20432947/57909986-bce4c100-78b6-11e9-8636-2c61bc6c45b9.png)

**Comment by bl0** [comment]
This may happen. Because the dqn in this repo is a fresh reimplementation and may perform better than the performance in the paper.
