### ISSUE TITLE
some different at DeepHash/model/dch/__init__.py

### ISSUE THREAD

**Issue by mengmengmengqiang** [thulab/DeepHash#3]
In DeepHash/model/dch/__init__.py , if method train return model.save_dir, which is a directory but not a model file. And then method validation use its returned value, so that it can't find the model file.
the following is error information
IsADirectoryError: [Errno 21] Is a directory: './models/'

I recommend that it should be return model.save_file

**Comment by bl0** [comment]
Thanks very much.

**Comment by mengmengmengqiang** [comment]
I have some confusion about Deep Cauchy Hash. Could I contact you with gmail ? And I will send an email later.

**Comment by bl0** [comment]
Yes!
Feel free to contact us!
