### ISSUE TITLE
Impact of data preprocessing

### ISSUE THREAD

**Issue by chenshen03** [thulab/DeepHash#31]
This code does not preprocess data, but HashNet does. 

Does data preprocessing have a big impact on results?

**Comment by bl0** [comment]
Can you tell more about preprocessing? What processing does HashNet use?

**Comment by chenshen03** [comment]
[HashNet:](https://github.com/thuml/HashNet)

![image](https://user-images.githubusercontent.com/20432947/58378949-0cba3b00-7fcf-11e9-8508-24dfad7d2c5e.png)

**Comment by bl0** [comment]
Hi, The RandomResizedCrop may improve the performance a little but we did not implement this in TensorFlow. If you want to know the impact, I suggest that you can change the RandomResizedCrop to Resize to see the difference.

BTW, our codes use 10-crops in the testing stage.

**Comment by chenshen03** [comment]
Thank you~
