### ISSUE TITLE
What's the effect of assign_lambda?

### ISSUE THREAD

**Issue by chenshen03** [thulab/DeepHash#32]
I found that removing assign_lambda had no effect on the results, and the training speed increased several times.
https://github.com/thulab/DeepHash/blob/0990a8d9760a37f5f41b0f9dbeb0173bbea614e3/DeepHash/model/dhn/dhn.py#L193-L194
Hence, what's the effect of aassign_lambda in codes?

**Comment by bl0** [comment]
Hi, it seems that assign_lambda is unnecessary. Thanks very much.
