### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by zq130320339** [thulab/DeepHash#33]
你好，您的DCH中cifra-10的数据集是如何划分的，比如train图片名为1_40.jpg,这两个数的含义是啥，您的论文中写到相似标签Sij,请问在代码什么位置？

**Comment by bl0** [comment]
DCH中cifra-10的数据集是按照论文中说的那样划分的。1_40.jpg没有什么实际的含义。s_ij在下述代码实现：
https://github.com/thulab/DeepHash/blob/904265c4a799848fd0fce93d521657ab44432cd6/DeepHash/model/dch/dch.py#L91

> CIFAR-10 is a standard dataset with 60,000 images in 10 classes. We follow protocol in [36, 3] to randomly select 100 images per class as query set, 500 images per class as training set, and the rest images are used as the database.
