### ISSUE TITLE
train

### ISSUE THREAD

**Issue by zq130320339** [thulab/DeepHash#34]
您好，现在换了自己的数据集，图片尺寸有要求吗？我将DeepHash/DeepHash/model/dch/dch.py 中49行代码改成self.img = tf.placeholder(tf.float32, [None, 416, 416, 3])，出现以下错误：
ValueError: Cannot feed value of shape (256, 256, 256, 3) for Tensor 'Placeholder:0', which has shape '(?, 416, 416, 3)'
如果我要更改图片的输入尺寸应如何修改代码

**Comment by bl0** [comment]
你好，图片尺寸是有要求的，必须是(256, 256, 3)，你可以把你的图片resize一下，或者修改一下网络的架构

**Comment by zq130320339** [comment]
修改网络结构是修改img_alexnet_layers吗

**Comment by bl0** [comment]
是的。

**Comment by zq130320339** [comment]
好的，谢谢
