### ISSUE TITLE
DTQ: Group Hard

### ISSUE THREAD

**Issue by hbellafkir** [thulab/DeepHash#37]
Hey, 
What is the purpose of using multiple groups, instead of using only one group and sample from it hard negatives with a given margin? Can the initial number of groups effect the MAP results?

**Comment by bl0** [comment]
If the selected triplets per epoch are too many, then during training, a lot of hard examples might not be hard anymore and potentially wasting most of the epoch. But with the proposed Group Hard, the number of selected triplets will be in a proper range and the outdated problem is alleviated.

**Comment by hbellafkir** [comment]
Thanks
