### ISSUE TITLE
实验结果与论文不一致

### ISSUE THREAD

**Issue by chenshen03** [thulab/DeepHash#38]
我采用这个代码默认的参数去实验，发现每个方法的实验结果都和论文有很大的差距。我不清楚是否自己参数设置有问题还是训练原因，亦或你们的代码实现和论文有点不同？
请问一下，是否方便能够共享下你们采用这DeepHash框架以及其默认参数，在各个方法下的实验结果吗？谢谢了~

**Comment by bl0** [comment]
参数可以参见这个issues。
https://github.com/thulab/DeepHash/issues/21

**Comment by chenshen03** [comment]
@bl0 嗯嗯，谢谢你的回复。参数设置我大概清楚，我只是想请问下能否分享下在这个框架下，你们在某个方法（比如DCH）下的mAP结果？因为我感觉我的实验结果和论文差距不小，谢谢了。

**Comment by bl0** [comment]
dch论文中的结果是在lr=5e-3, gamma=30，alpha=0.03下跑出来的。如果其他代码/参数一致的情况下你应该能复现论文中的结果。
抱歉由于精力有限没有去一一跑实验复现所有方法的所有结果，只是大致复现了一些，给你带来的不便，敬请谅解。如果有实在不能复现的，可以告诉我，我这边复现后告知你。

**Comment by chenshen03** [comment]
请问下alpha参数是什么，我没有在DCH的代码里找到其对应的作用地方。
其他方法的实验结果就不需要了，有DCH就足够了，我只是复现验证下，确保没有因为一些代码以外的因素影响实验结果。实在很感谢你的耐心解答！

**Comment by bl0** [comment]
我错了，alpha是一个dch里没有用到的参数，那就只有gamma需要调了。

注：在dhn里，用alpha来控制cross entropy的temperature。

**Comment by chenshen03** [comment]
谢谢了，请问方便加个微信吗。

**Comment by bl0** [comment]
私聊。
