### ISSUE TITLE
Train on multiple GPUs

### ISSUE THREAD

**Issue by hbellafkir** [thulab/DeepHash#39]
hey, 
Seems like the training is running only on one gpu despite given multiple gpus.

**Comment by bl0** [comment]
Hi, the models are all small enough to train in a single GPU, so we don't implement multi-gpu training. 
BTW, if you need multi-gpu training, please refer to the following example to modify the code.
https://github.com/tensorflow/models/blob/adc271722e512c8a55ef18b46c666a031de77774/tutorials/image/cifar10/cifar10_multi_gpu_train.py#L66
