### ISSUE TITLE
Mean pixel 

### ISSUE THREAD

**Issue by hbellafkir** [thulab/DeepHash#41]
hey @bl0 , 
I just want to note that the mean used here:  https://github.com/thulab/DeepHash/blob/d9d6aaf963e4666a9f2c097a8b00a8d8b7248b00/DeepHash/architecture/__init__.py#L50
is in BGR order, but it should be RGB since you swapped the image tensor to RGB here:
https://github.com/thulab/DeepHash/blob/d9d6aaf963e4666a9f2c097a8b00a8d8b7248b00/DeepHash/architecture/__init__.py#L15

**Comment by bl0** [comment]
Thanks for your issues, can you create a pull request for this? Then I can author you for the contribution.

But I think the pixel mean is not so important w.r.t performance.

**Comment by hbellafkir** [comment]
done
