### ISSUE TITLE
bad pre good recall about DCH?

### ISSUE THREAD

**Issue by InitAction** [thulab/DeepHash#43]
![prec](https://user-images.githubusercontent.com/17922501/60939309-bf3d2780-a309-11e9-9d96-61ee6ebfe449.jpg)
![rec](https://user-images.githubusercontent.com/17922501/60939320-c6fccc00-a309-11e9-90a2-66e4f3a46fb2.jpg)
![mAP](https://user-images.githubusercontent.com/17922501/60939328-c9f7bc80-a309-11e9-85cc-6894fd3fea99.jpg)

**Comment by InitAction** [comment]
@bl0 prec是什么原因呢会递减？训练数据为18个类别，总量在40w+

**Comment by bl0** [comment]
感觉你这个就是没学好。MAP值太低了。
而prec递减的原因，我感觉是通过学习把很多数据都拉到 raidus@2 里了。所以recall都接近1了，而prec一直在下降。

**Comment by InitAction** [comment]
@bl0 好的，谢谢。
