### ISSUE TITLE
您好，运行dhn时出现value

### ISSUE THREAD

**Issue by lidawang0802** [thulab/DeepHash#44]
你好，我在example/dhn的程序时出现了一个ValueError：ValueError: Object arrays cannot be loaded when allow_pickle=False，这个问题应该怎么解决呢？？？

<img width="354" alt="error" src="https://user-images.githubusercontent.com/53603814/62359935-677d8f00-b54a-11e9-8a59-fba0bad37fbd.png">

**Comment by bl0** [comment]
初步怀疑是你的python版本的问题。你用的是什么版本的python呢？

**Comment by chenshen03** [comment]
@lidawang0802 降低numpy版本，或则load时指定allow_pickle=True
