### ISSUE TITLE
DTQ Optimizer

### ISSUE THREAD

**Issue by hbellafkir** [thulab/DeepHash#45]
hi, 
is is there a reason for not using Adam as Optimizer ?

**Comment by Esmeriz** [comment]
Hi, @hbellafkir, did you perchance compare Adam with the Momentum? if so, could you please share your conclusion on this (and if you used it with CIFAR or other known dataset) ?

**Comment by hbellafkir** [comment]
It didn't work well for me on cifar10. The question why is still open.

**Comment by bl0** [comment]
Hi, Adam is really a good optimizer and can get good results without any hyperparameter tuning. In my view, however, the performance of Adam is usually a little lower than a well-tuned SGD.

**Comment by bl0** [comment]
I am closing this issue due to the long time of inactivity, feel free to reopen it if there is any question. Thanks!
