### ISSUE TITLE
DTQ - B-bit binary array

### ISSUE THREAD

**Issue by Esmeriz** [thulab/DeepHash#47]
From what I understood, both from the paper and the code, the concept here is to train a neural network through triplets to produce a B-bit array binary output that will allow an effective yet fast search image retrieval search. More so, I assume that when you state "compact binary codes" you are mentioning to **b** and, implicitly, to the "codes" of each image has in the code of this project.

However, when you try 8 bits, 16 bits, 32 bits on your benchmark, which of the args are you changing on the training script? the subspace? or the product of the subspace and the subcenter? I say this because in your code a default value is 

`parser.add_argument('--subspace', default=4, type=int)`
`parser.add_argument('--subcenter', default=256, type=int)`

In this case, is it 1024 bits?

**Comment by hbellafkir** [comment]
256 centers can be indexed with 8bit, so for 4 spaces we need 8x4=32bit, where each 8bit indicates a center from the appropriate space.

**Comment by bl0** [comment]
Thanks @hbellafkir 

I am closing this issue due to a long time of inactivity, feel free to reopen it if there is any question. Thanks!
