### ISSUE TITLE
DTQ binary codes

### ISSUE THREAD

**Issue by Esmeriz** [thulab/DeepHash#48]
From what I understood, after training DTQ for a specific purpose one has to do 2 things:

1. Run the algorithm on the database of images, storing the codes and centers for future search
2. Every time an image is submitted to retrieve the most similar ones the algorithm outputs a feature array z which will compare with the database of codes previously computed.

From this, if I want to add more images to the database then I have to run the algorithm again in order to update the codes for the images. Or is it possible just to compute the codes for the remaining images and add them to the database?

**Comment by Esmeriz** [comment]
Could someone please help me with this?

**Comment by bl0** [comment]
Actually, if the number of newly added images is not so large compared to that of the database, then the centers from old images are accurate enough. So that you can just compute the codes for the remaining images and add them to the database.

**Comment by bl0** [comment]
I am closing this issue due to the long time of inactivity, feel free to reopen it if there is any question. Thanks!
