### ISSUE TITLE
Not disjoint sets 

### ISSUE THREAD

**Issue by hbellafkir** [thulab/DeepHash#49]
hey, 
on Cifar10, test and database lists shares 888 out of 1000 test examples. train and database shares 4504 out of 5000 train examples. On Coco, train and database shares 1000 examples. Unfortunately this distorts the results.

**Comment by hbellafkir** [comment]
can I get an answer for that?

**Comment by bl0** [comment]
What do you mean of `distorts the results`? The setting we used in this repo is the standard-setting following the previous papers.

**Comment by hbellafkir** [comment]
Well, by removing the shared images from the database, the mAP on cifar10 drops form 78% to 77%. The train set must not contain examples from database and test.

**Comment by bl0** [comment]
Oh, you are right. I have updated the files. You can try the new data splits.

**Comment by bl0** [comment]
I am closing this issue due to the long time of inactivity, feel free to reopen it if there is any question. Thanks!
