### ISSUE TITLE
Where is this file, please?

### ISSUE THREAD

**Issue by Arthurgzb** [thulab/DeepHash#6]
I tried running the DVSQ code
Where is this file? {dataset}_wordvec.txt
    'wordvec_dict': "/home/caoyue/data/{dataset}/{dataset}_wordvec.txt".format(dataset=_dataset),

**Comment by bl0** [comment]
The following link may help!
https://github.com/caoyue10/cvpr17-dvsq/issues/4#issuecomment-346760005
