### ISSUE TITLE
No module named 'model' and data_provider

### ISSUE THREAD

**Issue by fanwenyuan** [thulab/DeepHash#9]
When I tried to run DCH with the train_val_script.py under its folder, got this error:ModuleNotFoundError: No module named 'model' in import model.dch as model.So how to solve it?

**Comment by bl0** [comment]
To import the pakcages implemented in ./DeepHash, we need to add the path of ./DeepHash to environment variables as:
```
export PYTHONPATH=/path/to/project/DeepHash/DeepHash:$PYTHONPATH
```

**Comment by bl0** [comment]
I am closing this issue due to the long time of inactivity, feel free to reopen it if there is any question. Thanks!

**Comment by SarahMasadeh** [comment]
When I tried to run DCH with the train_val_script.py under its folder, got this error:ModuleNotFoundError: No module named 'model' in import model.dch as model.So how to solve it?


To import the packages implemented in ./DeepHash, we need to add the path of ./DeepHash to environment variables as:

export PYTHONPATH=/path/to/project/DeepHash/DeepHash:$PYTHONPATH 
 My problem has not been resolved
